jobs:
  action:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Pull
        uses: actions/checkout@v2
      - name: Fetch Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./action/verify

name: Main

on:
  schedule:
    - cron: "5 0/3 * * *"
